accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign-up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name='portfolio'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:port_id>/', views.detail, name='detail'),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('search/', views.search, name="search"),
    path('<int:port_id>/edit', views.edit, name='edit'),
    path('<int:port_id>/update', views.update, name='update'),
    path('<int:port_id>/delete', views.delete, name="delete"), #이렇게 해야 url 형식 아니고 클릭으로 들어가는거
    path('<int:port_id>/like', views.like, name='like'),
]

private_equity/urls.py
from django.contrib import admin
from django.urls import path, include
#아래 두 줄은 Development 단계에서만 쓰이는 코드임.
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #이 줄 이해 안가 ㅠ

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
import pandas as pd

class Samofund(models.Model):
    #author = models.CharField(max_length=100) #필요없음 
    #foreignKey로 사용되는 변수는 나중에 데이터 꺼내올 때 지정해주는 이름 (table column명과 다를 수 있어)
    #on_delete=models.CASCADE : User가 사라지면 그 유저에 연동되었는 모든 것들 CASCADE처럼 다 지워버림 ! (optional)
    company_name = models.TextField(null=True) #non-nullable이 defaul라서 nullable로 바꿔주기 
    fund_name = models.TextField(null=True)
    initial_date = models.DateTimeField(null=True)
    m_strategy = models.TextField(null=True)
    pbs = models.TextField(null=True)
    setting = models.TextField(null=True)
    total_net_profit = models.TextField(null=True)
    modified_base = models.TextField(null=True)
    june_perf = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    week_perf = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    pday_perf = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    perf_2019 = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    year_conv_perf = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    cum_perf = models.DecimalField(null=True, decimal_places=2, max_digits=5)

    def __str__(self):
        return f'{self.fund_name},{self.pbs}'



# Create your models here.
class Portfolios(models.Model):
    #author = models.CharField(max_length=100) #필요없음 
    #foreignKey로 사용되는 변수는 나중에 데이터 꺼내올 때 지정해주는 이름 (table column명과 다를 수 있어)
    #on_delete=models.CASCADE : User가 사라지면 그 유저에 연동되었는 모든 것들 CASCADE처럼 다 지워버림 ! (optional)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False) #non-nullable이 defaul라서 nullable로 바꿔주기 
    body = models.TextField()
    image = models.ImageField(upload_to='portfolio',null=True) #이미지 자체를 다 저장하는 게 아니라(binary numbers), 이미지가 들어있는 '경로를' 저장해두는 것 
    created_at = models.DateTimeField()
    #포트폴리오 테이블에 추가하는 것처럼 보이지만, 별도의 테이블을 만드는 거야 
    #Portfolio.liked_users로 코딩해서 가져오려고 이름을 이렇게 지정한거지, 꼭 이 이름으로 할 필요 없엉 
    #User든지 Portfolio든지 어느 한 곳에만 추가하면 됨 (자동으로 다대다 )
    liked_users = models.ManyToManyField(User, related_name='liked_posts') #장고가 알아서 중간 테이블 만들어줌 -> User.liked_posts

    def __str__(self):
        #post.user인데 self가 instance니까 self.user 
        #이제 nullable이 되었으니까, 두가지 상황으로 나눠서 지정해줘야 함. 
        if self.user:
            return f'{self.user.get_username()}: {self.body}'
        #굳이 else 안써도 되니까 구태어 쓰지 않음 ! 
        return f'{self.body}'

portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import Portfolios
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    portfolio = Portfolios.objects.all().order_by('created_at')
    context = {'portfolio': portfolio}
    return render(request, 'portfolio/index.html', context)

def detail(request, port_id):
    portfolio = Portfolios.objects.get(id=port_id)
    context = {'portfolio': portfolio}
    return render(request, 'portfolio/detail.html', context)

@login_required
def new(request):
    #로그인 되어있지 않으면 로그인 페이지로 보내기 
    #login if문 대신에 그냥 로그인을 조건화하는 decorative code 
    #if not request.user.is_authenticated:
     #   return redirect('accounts:login') <= decorator 안에 accounts 앱 안의 login으로 가게 하기 때문에 앱을 만들 때 이름을 accounts로 하는 것 

    return render(request, 'portfolio/new.html')
#Question: 왜 여기서 한 번 더 해줘야 해? =========================================================Q 
@login_required
def create(request):
   # if not request.user.is_authenticated:
    #    return redirect('accounts:login')

    user = request.user #모든 유저는 request.user 안에 있음 
    body = request.POST['body']

    image = None #에러방지-Nullable variable 
    if 'image' in request.FILES:
        image = request.FILES['image']

    port = Portfolios(user=user, body=body, image=image, created_at=timezone.now()) 
    port.save()
    return redirect('portfolio:detail', port_id=port.id)
#-------------------------------------SEARCH FUNCTION-----------------------------
#Question) index함수 안에 만들어야하나? 
def search(request):
    if request.method == "POST":
        author = request.POST["fund"] #Question) input tag의 name을 넣는게 맞는지 확인
        #검색결과에 일치하는 author이 있는지 확인 
        fund = Portfolios.objects.get(author = author)
        if not fund:
            body = request.POST["fund"]
            #검색결과와 일치하는 body가 있는지 확인
            fund = Portfolios.objects.get(body = body)
        context = {'fund':fund}

        #찾은 검색결과랑 전체 리스트 전부 보여주기         
        return render(request, "portfolio/index.html", context)
    #get방식일 때는 다시 index함수로 가도록 하기 
    else:
        return render('portfolio:index')
#----------------------------------------------------------------------------------

@login_required
def edit(request, port_id):
    try:
        port = Portfolios.objects.get(id=port_id, user=request.user)
    except Portfolios.DoesNotExist:
        return redirect('portfolio:index')       
    context = {'port': port} 
    return render(request, 'portfolio/edit.html', context)

@login_required
def update(request, port_id):
    try:
        port = Portfolios.objects.get(id=port_id, user=request.user)
    except Portfolios.DoesNotExist:
        return redirect('portfolio:index')
    #port.author = request.POST['author']
    port.body = request.POST['body']
    if 'image' in request.FILES:
        port.image = request.FILES['image']
    port.save()
    return redirect('portfolio:detail', port_id=port.id)

@login_required
def delete(reqeust, port_id):
    try:
        port = Portfolios.objects.get(id=port_id)
    #Question: 여기서 왜 except error아니고?? ====================================Q 
    #Get함수에 대한 예외: DoesNotExist 
    except Portfolios.DoesNotExist:
        return redirect('portfolio:detail')
    port.delete()
    return redirect('portfolio:index')


#==========복습/==========
@login_required
def like(request, port_id):

    if request.method == 'POST':
        try:
            port = Portfolios.objects.get(id=port_id)

            if request.user in port.liked_users.all():
                port.liked_users.remove(request.user)
            else:
                port.liked_users.add(request.user)

            return redirect('portfolio:detail', port_id=port.id)

        except Portfolios.DoesNotExist:
            pass

    return redirect('portfolio:index')

portfolio/templates/portfolio/detail.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{%static 'portfolio/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
        <box>
        <h1>These are stocks of the week</h1>
        </box>

        {% if portfolio.image %}
        <div>
            <img src="{{ portfolio.image.url }}" alt="Portfolio Image"/>
        </div>
        {% endif %}
        
        {% if portfolio %}
        <h2>자산운용사</h2>
        <p>{{portfolio.user.get_username}}</p>

        <h2>Name of the Fund</h2>
        <p>{{portfolio.body}}</p>

        <h2>Updated Date</h2>
        <p>{{portfolio.created_at}}</p>
        {% else %}
            <p>No FUNDS</p>
        {% endif %}
<!--복습-->
        <div>좋아요 수: {{ portfolio.liked_users.count }}</div>
            {% if portfolio.user.is_authenticated %}
            <form action="{% url 'portfolio:like' portfolio.id %}" method="POST">
                {% csrf_token %}

                {% if user in portfolio.liked_users.all %}
                <button type="submit" class="btn btn-primary">LIKE</button>
                {% else %}
                <button type="submit" class="btn btn-secondary">LIKE</button>
                {% endif %}
            </form>
            {% endif %}
<!---->

        <a class="btn btn-primary" href="{% url 'portfolio:index' %}">목록</a>
        {% if user == portfolio.user %}
        <a class="btn btn-primary" href="{% url 'portfolio:edit' portfolio.id %}"> 수정하기 </a>
        <a class="btn btn-primary" href="{% url 'portfolio:delete' portfolio.id %}">삭제하기 </a>
        {% endif %} 

{% endblock %}

portfolio/templates/portfolio/edit.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{%static 'portfolio/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
        <box>
        <h1>Edit Post</h1>
        </box>
        <form action="{% url 'portfolio:update' port.id %}" method="POST">
            {% csrf_token %}
           <!-- <h2>자산운용사</h2>
            <input class="form-control"  type = "text" name="author" value="{{port.author}}"/> -->
            <h2>펀드명</h2>
            <textarea class="form-control" cols="20" rows="2" name="body"> {{port.body}} </textarea>
            <br>
            <div class="form-group">
                <label for="image">이미지</label>
                <input type="file" class="form-control-file" id="image" name="image">
            </div>
            <input class="btn btn-primary" type = "submit" value="수정하기" />
        </form>
        <a class="btn btn-primary" href="{% url 'portfolio:index' %}">목록</a>
        
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{%static 'portfolio/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <box>
        <img id="icon" src="{% static 'portfolio/images/icon.jpeg' %}"></img>
    </box>

    <form action="{% url 'portfolio:search' %}"  method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input autocomplete="off" autofocus class="form-control" name="fund" placeholder="What are you looking for?" type="text">
        </div>
        <button id="submit" class="btn btn-primary" type="submit">Search</button>
    </form><br><br>

    {% if fund %}
        <h4>{{ fund.author }} | {{ fund.body }} </h4>
    {% endif %}

        {% if portfolio %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>자산운용사</th>
                    <th>펀드명</th>
                    <th>게시일</th>
                    <th>상세</th>
                </tr>
            </thead>
            <tbody>
                {% for port in portfolio %}
                <tr>
                    <th>{{port.id}}</th>
                    <td>{{port.user.get_username}}</td>
                    <td>{{port.body}}</td>
                    <td>{{port.created_at}}</td>
                    <td><a href = "{% url 'portfolio:detail' port.id %}">보기</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>NO FUNDS FOUND</p>
        {% endif %}

        <a class="btn btn-primary btn-ii" href="{% url 'portfolio:new' %}">글쓰기</a>
{% endblock %}

portfolio/templates/portfolio/new.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{%static 'portfolio/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
  <box>
    <h1>New Post</h1>
  </box>  
    <form action="{% url 'portfolio:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      
      <h2>펀드명</h2>
      <textarea class="form-control" cols="20" rows="2" name="body"></textarea>
      <br />
      <div class="form-group">
        <label for="image">이미지</label>
        <input type="file" class="form-control-file" id="image" name="image"/>
      </div>
      <input class="btn btn-primary" type="submit" value="작성하기">
    </form>
    <a class="btn btn-primary" href="{% url 'portfolio:index' %}">목록</a>
{% endblock %}

<!--Label은 for, input은 id + name 필요! -->
<!--enctype: encoding type-->